#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"

#define TRAINER_NONE                            0
// Hoenn
#define TRAINER_SAWYER_1                        1
#define TRAINER_GRUNT_AQUA_HIDEOUT_1            2
#define TRAINER_GRUNT_AQUA_HIDEOUT_2            3
#define TRAINER_GRUNT_AQUA_HIDEOUT_3            4
#define TRAINER_GRUNT_AQUA_HIDEOUT_4            5
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_1         6
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_2         7
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_3         8
#define TRAINER_GABRIELLE_1                     9
#define TRAINER_GRUNT_PETALBURG_WOODS           10
#define TRAINER_MARCEL                          11
#define TRAINER_ALBERTO                         12
#define TRAINER_ED                              13
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_4         14
#define TRAINER_DECLAN                          15
#define TRAINER_GRUNT_RUSTURF_TUNNEL            16
#define TRAINER_GRUNT_WEATHER_INST_1            17
#define TRAINER_GRUNT_WEATHER_INST_2            18
#define TRAINER_GRUNT_WEATHER_INST_3            19
#define TRAINER_GRUNT_MUSEUM_1                  20
#define TRAINER_GRUNT_MUSEUM_2                  21
#define TRAINER_GRUNT_SPACE_CENTER_1            22
#define TRAINER_GRUNT_MT_PYRE_1                 23
#define TRAINER_GRUNT_MT_PYRE_2                 24
#define TRAINER_GRUNT_MT_PYRE_3                 25
#define TRAINER_GRUNT_WEATHER_INST_4            26
#define TRAINER_GRUNT_AQUA_HIDEOUT_5            27
#define TRAINER_GRUNT_AQUA_HIDEOUT_6            28
#define TRAINER_FREDRICK                        29
#define TRAINER_MATT                            30
#define TRAINER_ZANDER                          31
#define TRAINER_SHELLY_WEATHER_INSTITUTE        32
#define TRAINER_SHELLY_SEAFLOOR_CAVERN          33
#define TRAINER_ARCHIE                          34
#define TRAINER_LEAH                            35
#define TRAINER_DAISY                           36
#define TRAINER_ROSE_1                          37
#define TRAINER_FELIX                           38
#define TRAINER_VIOLET                          39
#define TRAINER_ROSE_2                          40
#define TRAINER_ROSE_3                          41
#define TRAINER_ROSE_4                          42
#define TRAINER_ROSE_5                          43
#define TRAINER_DUSTY_1                         44
#define TRAINER_CHIP                            45
#define TRAINER_FOSTER                          46
#define TRAINER_DUSTY_2                         47
#define TRAINER_DUSTY_3                         48
#define TRAINER_DUSTY_4                         49
#define TRAINER_DUSTY_5                         50
#define TRAINER_GABBY_AND_TY_1                  51
#define TRAINER_GABBY_AND_TY_2                  52
#define TRAINER_GABBY_AND_TY_3                  53
#define TRAINER_GABBY_AND_TY_4                  54
#define TRAINER_GABBY_AND_TY_5                  55
#define TRAINER_GABBY_AND_TY_6                  56
#define TRAINER_LOLA_1                          57
#define TRAINER_AUSTINA                         58
#define TRAINER_GWEN                            59
#define TRAINER_LOLA_2                          60
#define TRAINER_LOLA_3                          61
#define TRAINER_LOLA_4                          62
#define TRAINER_LOLA_5                          63
#define TRAINER_RICKY_1                         64
#define TRAINER_SIMON                           65
#define TRAINER_CHARLIE                         66
#define TRAINER_RICKY_2                         67
#define TRAINER_RICKY_3                         68
#define TRAINER_RICKY_4                         69
#define TRAINER_RICKY_5                         70
#define TRAINER_RANDALL                         71
#define TRAINER_PARKER                          72
#define TRAINER_GEORGE                          73
#define TRAINER_BERKE                           74
#define TRAINER_BRAXTON                         75
#define TRAINER_VINCENT                         76
#define TRAINER_LEROY                           77
#define TRAINER_WILTON_1                        78
#define TRAINER_EDGAR                           79
#define TRAINER_ALBERT                          80
#define TRAINER_SAMUEL                          81
#define TRAINER_VITO                            82
#define TRAINER_OWEN                            83
#define TRAINER_WILTON_2                        84
#define TRAINER_WILTON_3                        85
#define TRAINER_WILTON_4                        86
#define TRAINER_WILTON_5                        87
#define TRAINER_WARREN                          88
#define TRAINER_MARY                            89
#define TRAINER_ALEXIA                          90
#define TRAINER_JODY                            91
#define TRAINER_WENDY                           92
#define TRAINER_KEIRA                           93
#define TRAINER_BROOKE_1                        94
#define TRAINER_JENNIFER                        95
#define TRAINER_HOPE                            96
#define TRAINER_SHANNON                         97
#define TRAINER_MICHELLE                        98
#define TRAINER_CAROLINE                        99
#define TRAINER_JULIE                           100
#define TRAINER_BROOKE_2                        101
#define TRAINER_BROOKE_3                        102
#define TRAINER_BROOKE_4                        103
#define TRAINER_BROOKE_5                        104
#define TRAINER_PATRICIA                        105
#define TRAINER_KINDRA                          106
#define TRAINER_TAMMY                           107
#define TRAINER_VALERIE_1                       108
#define TRAINER_TASHA                           109
#define TRAINER_VALERIE_2                       110
#define TRAINER_VALERIE_3                       111
#define TRAINER_VALERIE_4                       112
#define TRAINER_VALERIE_5                       113
#define TRAINER_CINDY_1                         114
#define TRAINER_DAPHNE                          115
#define TRAINER_GRUNT_SPACE_CENTER_2            116
#define TRAINER_CINDY_2                         117
#define TRAINER_BRIANNA                         118
#define TRAINER_NAOMI                           119
#define TRAINER_CINDY_3                         120
#define TRAINER_CINDY_4                         121
#define TRAINER_CINDY_5                         122
#define TRAINER_CINDY_6                         123
#define TRAINER_MELISSA                         124
#define TRAINER_SHEILA                          125
#define TRAINER_SHIRLEY                         126
#define TRAINER_JESSICA_1                       127
#define TRAINER_CONNIE                          128
#define TRAINER_BRIDGET                         129
#define TRAINER_OLIVIA                          130
#define TRAINER_TIFFANY                         131
#define TRAINER_JESSICA_2                       132
#define TRAINER_JESSICA_3                       133
#define TRAINER_JESSICA_4                       134
#define TRAINER_JESSICA_5                       135
#define TRAINER_WINSTON_1                       136
#define TRAINER_MOLLIE                          137
#define TRAINER_GARRET                          138
#define TRAINER_WINSTON_2                       139
#define TRAINER_WINSTON_3                       140
#define TRAINER_WINSTON_4                       141
#define TRAINER_WINSTON_5                       142
#define TRAINER_STEVE_1                         143
#define TRAINER_THALIA_1                        144
#define TRAINER_MARK                            145
#define TRAINER_GRUNT_MT_CHIMNEY_1              146
#define TRAINER_STEVE_2                         147
#define TRAINER_STEVE_3                         148
#define TRAINER_STEVE_4                         149
#define TRAINER_STEVE_5                         150
#define TRAINER_LUIS                            151
#define TRAINER_DOMINIK                         152
#define TRAINER_DOUGLAS                         153
#define TRAINER_DARRIN                          154
#define TRAINER_TONY_1                          155
#define TRAINER_JEROME                          156
#define TRAINER_MATTHEW                         157
#define TRAINER_DAVID                           158
#define TRAINER_SPENCER                         159
#define TRAINER_ROLAND                          160
#define TRAINER_NOLEN                           161
#define TRAINER_STAN                            162
#define TRAINER_BARRY                           163
#define TRAINER_DEAN                            164
#define TRAINER_RODNEY                          165
#define TRAINER_RICHARD                         166
#define TRAINER_HERMAN                          167
#define TRAINER_SANTIAGO                        168
#define TRAINER_GILBERT                         169
#define TRAINER_FRANKLIN                        170
#define TRAINER_KEVIN                           171
#define TRAINER_JACK                            172
#define TRAINER_DUDLEY                          173
#define TRAINER_CHAD                            174
#define TRAINER_TONY_2                          175
#define TRAINER_TONY_3                          176
#define TRAINER_TONY_4                          177
#define TRAINER_TONY_5                          178
#define TRAINER_TAKAO                           179
#define TRAINER_HITOSHI                         180
#define TRAINER_KIYO                            181
#define TRAINER_KOICHI                          182
#define TRAINER_NOB_1                           183
#define TRAINER_NOB_2                           184
#define TRAINER_NOB_3                           185
#define TRAINER_NOB_4                           186
#define TRAINER_NOB_5                           187
#define TRAINER_YUJI                            188
#define TRAINER_DAISUKE                         189
#define TRAINER_ATSUSHI                         190
#define TRAINER_KIRK                            191
#define TRAINER_GRUNT_AQUA_HIDEOUT_7            192
#define TRAINER_GRUNT_AQUA_HIDEOUT_8            193
#define TRAINER_SHAWN                           194
#define TRAINER_FERNANDO_1                      195
#define TRAINER_DALTON_1                        196
#define TRAINER_DALTON_2                        197
#define TRAINER_DALTON_3                        198
#define TRAINER_DALTON_4                        199
#define TRAINER_DALTON_5                        200
#define TRAINER_COLE                            201
#define TRAINER_JEFF                            202
#define TRAINER_AXLE                            203
#define TRAINER_JACE                            204
#define TRAINER_KEEGAN                          205
#define TRAINER_BERNIE_1                        206
#define TRAINER_BERNIE_2                        207
#define TRAINER_BERNIE_3                        208
#define TRAINER_BERNIE_4                        209
#define TRAINER_BERNIE_5                        210
#define TRAINER_DREW                            211
#define TRAINER_BEAU                            212
#define TRAINER_LARRY                           213
#define TRAINER_SHANE                           214
#define TRAINER_JUSTIN                          215
#define TRAINER_ETHAN_1                         216
#define TRAINER_AUTUMN                          217
#define TRAINER_TRAVIS                          218
#define TRAINER_ETHAN_2                         219
#define TRAINER_ETHAN_3                         220
#define TRAINER_ETHAN_4                         221
#define TRAINER_ETHAN_5                         222
#define TRAINER_BRENT                           223
#define TRAINER_DONALD                          224
#define TRAINER_TAYLOR                          225
#define TRAINER_JEFFREY_1                       226
#define TRAINER_DEREK                           227
#define TRAINER_JEFFREY_2                       228
#define TRAINER_JEFFREY_3                       229
#define TRAINER_JEFFREY_4                       230
#define TRAINER_JEFFREY_5                       231
#define TRAINER_EDWARD                          232
#define TRAINER_PRESTON                         233
#define TRAINER_VIRGIL                          234
#define TRAINER_BLAKE                           235
#define TRAINER_WILLIAM                         236
#define TRAINER_JOSHUA                          237
#define TRAINER_CAMERON_1                       238
#define TRAINER_CAMERON_2                       239
#define TRAINER_CAMERON_3                       240
#define TRAINER_CAMERON_4                       241
#define TRAINER_CAMERON_5                       242
#define TRAINER_JACLYN                          243
#define TRAINER_HANNAH                          244
#define TRAINER_SAMANTHA                        245
#define TRAINER_MAURA                           246
#define TRAINER_KAYLA                           247
#define TRAINER_ALEXIS                          248
#define TRAINER_JACKI_1                         249
#define TRAINER_JACKI_2                         250
#define TRAINER_JACKI_3                         251
#define TRAINER_JACKI_4                         252
#define TRAINER_JACKI_5                         253
#define TRAINER_WALTER_1                        254
#define TRAINER_MICAH                           255
#define TRAINER_THOMAS                          256
#define TRAINER_WALTER_2                        257
#define TRAINER_WALTER_3                        258
#define TRAINER_WALTER_4                        259
#define TRAINER_WALTER_5                        260
#define TRAINER_SIDNEY                          261
#define TRAINER_PHOEBE                          262
#define TRAINER_GLACIA                          263
#define TRAINER_DRAKE                           264
#define TRAINER_ROXANNE_1                       265
#define TRAINER_BRAWLY_1                        266
#define TRAINER_WATTSON_1                       267
#define TRAINER_FLANNERY_1                      268
#define TRAINER_NORMAN_1                        269
#define TRAINER_WINONA_1                        270
#define TRAINER_TATE_AND_LIZA_1                 271
#define TRAINER_JUAN_1                          272
#define TRAINER_JERRY_1                         273
#define TRAINER_TED                             274
#define TRAINER_PAUL                            275
#define TRAINER_JERRY_2                         276
#define TRAINER_JERRY_3                         277
#define TRAINER_JERRY_4                         278
#define TRAINER_JERRY_5                         279
#define TRAINER_KAREN_1                         280
#define TRAINER_GEORGIA                         281
#define TRAINER_KAREN_2                         282
#define TRAINER_KAREN_3                         283
#define TRAINER_KAREN_4                         284
#define TRAINER_KAREN_5                         285
#define TRAINER_KATE_AND_JOY                    286
#define TRAINER_ANNA_AND_MEG_1                  287
#define TRAINER_ANNA_AND_MEG_2                  288
#define TRAINER_ANNA_AND_MEG_3                  289
#define TRAINER_ANNA_AND_MEG_4                  290
#define TRAINER_ANNA_AND_MEG_5                  291
#define TRAINER_VICTOR                          292
#define TRAINER_MIGUEL_1                        293
#define TRAINER_COLTON                          294
#define TRAINER_MIGUEL_2                        295
#define TRAINER_MIGUEL_3                        296
#define TRAINER_MIGUEL_4                        297
#define TRAINER_MIGUEL_5                        298
#define TRAINER_VICTORIA                        299
#define TRAINER_VANESSA                         300
#define TRAINER_BETHANY                         301
#define TRAINER_ISABEL_1                        302
#define TRAINER_ISABEL_2                        303
#define TRAINER_ISABEL_3                        304
#define TRAINER_ISABEL_4                        305
#define TRAINER_ISABEL_5                        306
#define TRAINER_TIMOTHY_1                       307
#define TRAINER_TIMOTHY_2                       308
#define TRAINER_TIMOTHY_3                       309
#define TRAINER_TIMOTHY_4                       310
#define TRAINER_TIMOTHY_5                       311
#define TRAINER_VICKY                           312
#define TRAINER_SHELBY_1                        313
#define TRAINER_SHELBY_2                        314
#define TRAINER_SHELBY_3                        315
#define TRAINER_SHELBY_4                        316
#define TRAINER_SHELBY_5                        317
#define TRAINER_CALVIN_1                        318
#define TRAINER_BILLY                           319
#define TRAINER_JOSH                            320
#define TRAINER_TOMMY                           321
#define TRAINER_JOEY                            322
#define TRAINER_BEN                             323
#define TRAINER_QUINCY                          324
#define TRAINER_KATELYNN                        325
#define TRAINER_JAYLEN                          326
#define TRAINER_DILLON                          327
#define TRAINER_CALVIN_2                        328
#define TRAINER_CALVIN_3                        329
#define TRAINER_CALVIN_4                        330
#define TRAINER_CALVIN_5                        331
#define TRAINER_EDDIE                           332
#define TRAINER_ALLEN                           333
#define TRAINER_TIMMY                           334
#define TRAINER_WALLACE                         335
#define TRAINER_ANDREW                          336
#define TRAINER_IVAN                            337
#define TRAINER_CLAUDE                          338
#define TRAINER_ELLIOT_1                        339
#define TRAINER_NED                             340
#define TRAINER_DALE                            341
#define TRAINER_NOLAN                           342
#define TRAINER_BARNY                           343
#define TRAINER_WADE                            344
#define TRAINER_CARTER                          345
#define TRAINER_ELLIOT_2                        346
#define TRAINER_ELLIOT_3                        347
#define TRAINER_ELLIOT_4                        348
#define TRAINER_ELLIOT_5                        349
#define TRAINER_RONALD                          350
#define TRAINER_JACOB                           351
#define TRAINER_ANTHONY                         352
#define TRAINER_BENJAMIN_1                      353
#define TRAINER_BENJAMIN_2                      354
#define TRAINER_BENJAMIN_3                      355
#define TRAINER_BENJAMIN_4                      356
#define TRAINER_BENJAMIN_5                      357
#define TRAINER_ABIGAIL_1                       358
#define TRAINER_JASMINE                         359
#define TRAINER_ABIGAIL_2                       360
#define TRAINER_ABIGAIL_3                       361
#define TRAINER_ABIGAIL_4                       362
#define TRAINER_ABIGAIL_5                       363
#define TRAINER_DYLAN_1                         364
#define TRAINER_DYLAN_2                         365
#define TRAINER_DYLAN_3                         366
#define TRAINER_DYLAN_4                         367
#define TRAINER_DYLAN_5                         368
#define TRAINER_MARIA_1                         369
#define TRAINER_MARIA_2                         370
#define TRAINER_MARIA_3                         371
#define TRAINER_MARIA_4                         372
#define TRAINER_MARIA_5                         373
#define TRAINER_CAMDEN                          374
#define TRAINER_DEMETRIUS                       375
#define TRAINER_ISAIAH_1                        376
#define TRAINER_PABLO_1                         377
#define TRAINER_CHASE                           378
#define TRAINER_ISAIAH_2                        379
#define TRAINER_ISAIAH_3                        380
#define TRAINER_ISAIAH_4                        381
#define TRAINER_ISAIAH_5                        382
#define TRAINER_ISOBEL                          383
#define TRAINER_DONNY                           384
#define TRAINER_TALIA                           385
#define TRAINER_KATELYN_1                       386
#define TRAINER_ALLISON                         387
#define TRAINER_KATELYN_2                       388
#define TRAINER_KATELYN_3                       389
#define TRAINER_KATELYN_4                       390
#define TRAINER_KATELYN_5                       391
#define TRAINER_NICOLAS_1                       392
#define TRAINER_NICOLAS_2                       393
#define TRAINER_NICOLAS_3                       394
#define TRAINER_NICOLAS_4                       395
#define TRAINER_NICOLAS_5                       396
#define TRAINER_AARON                           397
#define TRAINER_PERRY                           398
#define TRAINER_HUGH                            399
#define TRAINER_PHIL                            400
#define TRAINER_JARED                           401
#define TRAINER_HUMBERTO                        402
#define TRAINER_PRESLEY                         403
#define TRAINER_EDWARDO                         404
#define TRAINER_COLIN                           405
#define TRAINER_ROBERT_1                        406
#define TRAINER_BENNY                           407
#define TRAINER_CHESTER                         408
#define TRAINER_ROBERT_2                        409
#define TRAINER_ROBERT_3                        410
#define TRAINER_ROBERT_4                        411
#define TRAINER_ROBERT_5                        412
#define TRAINER_ALEX                            413
#define TRAINER_BECK                            414
#define TRAINER_YASU                            415
#define TRAINER_TAKASHI                         416
#define TRAINER_DIANNE                          417
#define TRAINER_JANI                            418
#define TRAINER_LAO_1                           419
#define TRAINER_LUNG                            420
#define TRAINER_LAO_2                           421
#define TRAINER_LAO_3                           422
#define TRAINER_LAO_4                           423
#define TRAINER_LAO_5                           424
#define TRAINER_JOCELYN                         425
#define TRAINER_LAURA                           426
#define TRAINER_CYNDY_1                         427
#define TRAINER_CORA                            428
#define TRAINER_PAULA                           429
#define TRAINER_CYNDY_2                         430
#define TRAINER_CYNDY_3                         431
#define TRAINER_CYNDY_4                         432
#define TRAINER_CYNDY_5                         433
#define TRAINER_MADELINE_1                      434
#define TRAINER_CLARISSA                        435
#define TRAINER_ANGELICA                        436
#define TRAINER_MADELINE_2                      437
#define TRAINER_MADELINE_3                      438
#define TRAINER_MADELINE_4                      439
#define TRAINER_MADELINE_5                      440
#define TRAINER_BEVERLY                         441
#define TRAINER_IMANI                           442
#define TRAINER_KYLA                            443
#define TRAINER_DENISE                          444
#define TRAINER_BETH                            445
#define TRAINER_TARA                            446
#define TRAINER_MISSY                           447
#define TRAINER_ALICE                           448
#define TRAINER_JENNY_1                         449
#define TRAINER_GRACE                           450
#define TRAINER_TANYA                           451
#define TRAINER_SHARON                          452
#define TRAINER_NIKKI                           453
#define TRAINER_BRENDA                          454
#define TRAINER_KATIE                           455
#define TRAINER_SUSIE                           456
#define TRAINER_KARA                            457
#define TRAINER_DANA                            458
#define TRAINER_SIENNA                          459
#define TRAINER_DEBRA                           460
#define TRAINER_LINDA                           461
#define TRAINER_KAYLEE                          462
#define TRAINER_LAUREL                          463
#define TRAINER_CARLEE                          464
#define TRAINER_JENNY_2                         465
#define TRAINER_JENNY_3                         466
#define TRAINER_JENNY_4                         467
#define TRAINER_JENNY_5                         468
#define TRAINER_HEIDI                           469
#define TRAINER_BECKY                           470
#define TRAINER_CAROL                           471
#define TRAINER_NANCY                           472
#define TRAINER_MARTHA                          473
#define TRAINER_DIANA_1                         474
#define TRAINER_CEDRIC                          475
#define TRAINER_IRENE                           476
#define TRAINER_DIANA_2                         477
#define TRAINER_DIANA_3                         478
#define TRAINER_DIANA_4                         479
#define TRAINER_DIANA_5                         480
#define TRAINER_AMY_AND_LIV_1                   481
#define TRAINER_AMY_AND_LIV_2                   482
#define TRAINER_GINA_AND_MIA_1                  483
#define TRAINER_MIU_AND_YUKI                    484
#define TRAINER_AMY_AND_LIV_3                   485
#define TRAINER_GINA_AND_MIA_2                  486
#define TRAINER_AMY_AND_LIV_4                   487
#define TRAINER_AMY_AND_LIV_5                   488
#define TRAINER_AMY_AND_LIV_6                   489
#define TRAINER_HUEY                            490
#define TRAINER_EDMOND                          491
#define TRAINER_ERNEST_1                        492
#define TRAINER_DWAYNE                          493
#define TRAINER_PHILLIP                         494
#define TRAINER_LEONARD                         495
#define TRAINER_DUNCAN                          496
#define TRAINER_ERNEST_2                        497
#define TRAINER_ERNEST_3                        498
#define TRAINER_ERNEST_4                        499
#define TRAINER_ERNEST_5                        500
#define TRAINER_ELI                             501
#define TRAINER_ANNIKA                          502
#define TRAINER_JAZMYN                          503
#define TRAINER_JONAS                           504
#define TRAINER_KAYLEY                          505
#define TRAINER_AURON                           506
#define TRAINER_KELVIN                          507
#define TRAINER_MARLEY                          508
#define TRAINER_REYNA                           509
#define TRAINER_HUDSON                          510
#define TRAINER_CONOR                           511
#define TRAINER_EDWIN_1                         512
#define TRAINER_HECTOR                          513
#define TRAINER_TABITHA_MOSSDEEP                514
#define TRAINER_EDWIN_2                         515
#define TRAINER_EDWIN_3                         516
#define TRAINER_EDWIN_4                         517
#define TRAINER_EDWIN_5                         518
#define TRAINER_WALLY_VR_1                      519
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP        520
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP        521
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP        522
#define TRAINER_BRENDAN_ROUTE_103_TREECKO       523
#define TRAINER_BRENDAN_ROUTE_110_TREECKO       524
#define TRAINER_BRENDAN_ROUTE_119_TREECKO       525
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC       526
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC       527
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC       528
#define TRAINER_MAY_ROUTE_103_MUDKIP            529
#define TRAINER_MAY_ROUTE_110_MUDKIP            530
#define TRAINER_MAY_ROUTE_119_MUDKIP            531
#define TRAINER_MAY_ROUTE_103_TREECKO           532
#define TRAINER_MAY_ROUTE_110_TREECKO           533
#define TRAINER_MAY_ROUTE_119_TREECKO           534
#define TRAINER_MAY_ROUTE_103_TORCHIC           535
#define TRAINER_MAY_ROUTE_110_TORCHIC           536
#define TRAINER_MAY_ROUTE_119_TORCHIC           537
#define TRAINER_ISAAC_1                         538
#define TRAINER_DAVIS                           539
#define TRAINER_MITCHELL                        540
#define TRAINER_ISAAC_2                         541
#define TRAINER_ISAAC_3                         542
#define TRAINER_ISAAC_4                         543
#define TRAINER_ISAAC_5                         544
#define TRAINER_LYDIA_1                         545
#define TRAINER_HALLE                           546
#define TRAINER_GARRISON                        547
#define TRAINER_LYDIA_2                         548
#define TRAINER_LYDIA_3                         549
#define TRAINER_LYDIA_4                         550
#define TRAINER_LYDIA_5                         551
#define TRAINER_JACKSON_1                       552
#define TRAINER_LORENZO                         553
#define TRAINER_SEBASTIAN                       554
#define TRAINER_JACKSON_2                       555
#define TRAINER_JACKSON_3                       556
#define TRAINER_JACKSON_4                       557
#define TRAINER_JACKSON_5                       558
#define TRAINER_CATHERINE_1                     559
#define TRAINER_JENNA                           560
#define TRAINER_SOPHIA                          561
#define TRAINER_CATHERINE_2                     562
#define TRAINER_CATHERINE_3                     563
#define TRAINER_CATHERINE_4                     564
#define TRAINER_CATHERINE_5                     565
#define TRAINER_JULIO                           566
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5         567
#define TRAINER_GRUNT_UNUSED                    568
#define TRAINER_GRUNT_MT_PYRE_4                 569
#define TRAINER_GRUNT_JAGGED_PASS               570
#define TRAINER_MARC                            571
#define TRAINER_BRENDEN                         572
#define TRAINER_LILITH                          573
#define TRAINER_CRISTIAN                        574
#define TRAINER_SYLVIA                          575
#define TRAINER_LEONARDO                        576
#define TRAINER_ATHENA                          577
#define TRAINER_HARRISON                        578
#define TRAINER_GRUNT_MT_CHIMNEY_2              579
#define TRAINER_CLARENCE                        580
#define TRAINER_TERRY                           581
#define TRAINER_NATE                            582
#define TRAINER_KATHLEEN                        583
#define TRAINER_CLIFFORD                        584
#define TRAINER_NICHOLAS                        585
#define TRAINER_GRUNT_SPACE_CENTER_3            586
#define TRAINER_GRUNT_SPACE_CENTER_4            587
#define TRAINER_GRUNT_SPACE_CENTER_5            588
#define TRAINER_GRUNT_SPACE_CENTER_6            589
#define TRAINER_GRUNT_SPACE_CENTER_7            590
#define TRAINER_MACEY                           591
#define TRAINER_BRENDAN_RUSTBORO_TREECKO        592
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP         593
#define TRAINER_PAXTON                          594
#define TRAINER_ISABELLA                        595
#define TRAINER_GRUNT_WEATHER_INST_5            596
#define TRAINER_TABITHA_MT_CHIMNEY              597
#define TRAINER_JONATHAN                        598
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC        599
#define TRAINER_MAY_RUSTBORO_MUDKIP             600
#define TRAINER_MAXIE_MAGMA_HIDEOUT             601
#define TRAINER_MAXIE_MT_CHIMNEY                602
#define TRAINER_TIANA                           603
#define TRAINER_HALEY_1                         604
#define TRAINER_JANICE                          605
#define TRAINER_VIVI                            606
#define TRAINER_HALEY_2                         607
#define TRAINER_HALEY_3                         608
#define TRAINER_HALEY_4                         609
#define TRAINER_HALEY_5                         610
#define TRAINER_SALLY                           611
#define TRAINER_ROBIN                           612
#define TRAINER_ANDREA                          613
#define TRAINER_CRISSY                          614
#define TRAINER_RICK                            615
#define TRAINER_LYLE                            616
#define TRAINER_JOSE                            617
#define TRAINER_DOUG                            618
#define TRAINER_GREG                            619
#define TRAINER_KENT                            620
#define TRAINER_JAMES_1                         621
#define TRAINER_JAMES_2                         622
#define TRAINER_JAMES_3                         623
#define TRAINER_JAMES_4                         624
#define TRAINER_JAMES_5                         625
#define TRAINER_BRICE                           626
#define TRAINER_TRENT_1                         627
#define TRAINER_LENNY                           628
#define TRAINER_LUCAS_1                         629
#define TRAINER_ALAN                            630
#define TRAINER_CLARK                           631
#define TRAINER_ERIC                            632
#define TRAINER_LUCAS_2                         633
#define TRAINER_MIKE_1                          634
#define TRAINER_MIKE_2                          635
#define TRAINER_TRENT_2                         636
#define TRAINER_TRENT_3                         637
#define TRAINER_TRENT_4                         638
#define TRAINER_TRENT_5                         639
#define TRAINER_DEZ_AND_LUKE                    640
#define TRAINER_LEA_AND_JED                     641
#define TRAINER_KIRA_AND_DAN_1                  642
#define TRAINER_KIRA_AND_DAN_2                  643
#define TRAINER_KIRA_AND_DAN_3                  644
#define TRAINER_KIRA_AND_DAN_4                  645
#define TRAINER_KIRA_AND_DAN_5                  646
#define TRAINER_JOHANNA                         647
#define TRAINER_GERALD                          648
#define TRAINER_VIVIAN                          649
#define TRAINER_DANIELLE                        650
#define TRAINER_HIDEO                           651
#define TRAINER_KEIGO                           652
#define TRAINER_RILEY                           653
#define TRAINER_FLINT                           654
#define TRAINER_ASHLEY                          655
#define TRAINER_WALLY_MAUVILLE                  656
#define TRAINER_WALLY_VR_2                      657
#define TRAINER_WALLY_VR_3                      658
#define TRAINER_WALLY_VR_4                      659
#define TRAINER_WALLY_VR_5                      660
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP         661
#define TRAINER_BRENDAN_LILYCOVE_TREECKO        662
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC        663
#define TRAINER_MAY_LILYCOVE_MUDKIP             664
#define TRAINER_MAY_LILYCOVE_TREECKO            665
#define TRAINER_MAY_LILYCOVE_TORCHIC            666
#define TRAINER_JONAH                           667
#define TRAINER_HENRY                           668
#define TRAINER_ROGER                           669
#define TRAINER_ALEXA                           670
#define TRAINER_RUBEN                           671
#define TRAINER_KOJI_1                          672
#define TRAINER_WAYNE                           673
#define TRAINER_AIDAN                           674
#define TRAINER_REED                            675
#define TRAINER_TISHA                           676
#define TRAINER_TORI_AND_TIA                    677
#define TRAINER_KIM_AND_IRIS                    678
#define TRAINER_TYRA_AND_IVY                    679
#define TRAINER_MEL_AND_PAUL                    680
#define TRAINER_JOHN_AND_JAY_1                  681
#define TRAINER_JOHN_AND_JAY_2                  682
#define TRAINER_JOHN_AND_JAY_3                  683
#define TRAINER_JOHN_AND_JAY_4                  684
#define TRAINER_JOHN_AND_JAY_5                  685
#define TRAINER_RELI_AND_IAN                    686
#define TRAINER_LILA_AND_ROY_1                  687
#define TRAINER_LILA_AND_ROY_2                  688
#define TRAINER_LILA_AND_ROY_3                  689
#define TRAINER_LILA_AND_ROY_4                  690
#define TRAINER_LILA_AND_ROY_5                  691
#define TRAINER_LISA_AND_RAY                    692
#define TRAINER_CHRIS                           693
#define TRAINER_DAWSON                          694
#define TRAINER_SARAH                           695
#define TRAINER_DARIAN                          696
#define TRAINER_HAILEY                          697
#define TRAINER_CHANDLER                        698
#define TRAINER_KALEB                           699
#define TRAINER_JOSEPH                          700
#define TRAINER_ALYSSA                          701
#define TRAINER_MARCOS                          702
#define TRAINER_RHETT                           703
#define TRAINER_TYRON                           704
#define TRAINER_CELINA                          705
#define TRAINER_BIANCA                          706
#define TRAINER_HAYDEN                          707
#define TRAINER_SOPHIE                          708
#define TRAINER_COBY                            709
#define TRAINER_LAWRENCE                        710
#define TRAINER_WYATT                           711
#define TRAINER_ANGELINA                        712
#define TRAINER_KAI                             713
#define TRAINER_CHARLOTTE                       714
#define TRAINER_DEANDRE                         715
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1           716
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2           717
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3           718
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4           719
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5           720
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6           721
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7           722
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8           723
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9           724
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10          725
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11          726
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12          727
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13          728
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14          729
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15          730
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16          731
#define TRAINER_TABITHA_MAGMA_HIDEOUT           732
#define TRAINER_DARCY                           733
#define TRAINER_MAXIE_MOSSDEEP                  734
#define TRAINER_PETE                            735
#define TRAINER_ISABELLE                        736
#define TRAINER_ANDRES_1                        737
#define TRAINER_JOSUE                           738
#define TRAINER_CAMRON                          739
#define TRAINER_CORY_1                          740
#define TRAINER_CAROLINA                        741
#define TRAINER_ELIJAH                          742
#define TRAINER_CELIA                           743
#define TRAINER_BRYAN                           744
#define TRAINER_BRANDEN                         745
#define TRAINER_BRYANT                          746
#define TRAINER_SHAYLA                          747
#define TRAINER_KYRA                            748
#define TRAINER_JAIDEN                          749
#define TRAINER_ALIX                            750
#define TRAINER_HELENE                          751
#define TRAINER_MARLENE                         752
#define TRAINER_DEVAN                           753
#define TRAINER_JOHNSON                         754
#define TRAINER_MELINA                          755
#define TRAINER_BRANDI                          756
#define TRAINER_AISHA                           757
#define TRAINER_MAKAYLA                         758
#define TRAINER_FABIAN                          759
#define TRAINER_DAYTON                          760
#define TRAINER_RACHEL                          761
#define TRAINER_LEONEL                          762
#define TRAINER_CALLIE                          763
#define TRAINER_CALE                            764
#define TRAINER_MYLES                           765
#define TRAINER_PAT                             766
#define TRAINER_CRISTIN_1                       767
#define TRAINER_MAY_RUSTBORO_TREECKO            768
#define TRAINER_MAY_RUSTBORO_TORCHIC            769
#define TRAINER_ROXANNE_2                       770
#define TRAINER_ROXANNE_3                       771
#define TRAINER_ROXANNE_4                       772
#define TRAINER_ROXANNE_5                       773
#define TRAINER_BRAWLY_2                        774
#define TRAINER_BRAWLY_3                        775
#define TRAINER_BRAWLY_4                        776
#define TRAINER_BRAWLY_5                        777
#define TRAINER_WATTSON_2                       778
#define TRAINER_WATTSON_3                       779
#define TRAINER_WATTSON_4                       780
#define TRAINER_WATTSON_5                       781
#define TRAINER_FLANNERY_2                      782
#define TRAINER_FLANNERY_3                      783
#define TRAINER_FLANNERY_4                      784
#define TRAINER_FLANNERY_5                      785
#define TRAINER_NORMAN_2                        786
#define TRAINER_NORMAN_3                        787
#define TRAINER_NORMAN_4                        788
#define TRAINER_NORMAN_5                        789
#define TRAINER_WINONA_2                        790
#define TRAINER_WINONA_3                        791
#define TRAINER_WINONA_4                        792
#define TRAINER_WINONA_5                        793
#define TRAINER_TATE_AND_LIZA_2                 794
#define TRAINER_TATE_AND_LIZA_3                 795
#define TRAINER_TATE_AND_LIZA_4                 796
#define TRAINER_TATE_AND_LIZA_5                 797
#define TRAINER_JUAN_2                          798
#define TRAINER_JUAN_3                          799
#define TRAINER_JUAN_4                          800
#define TRAINER_JUAN_5                          801
#define TRAINER_ANGELO                          802
#define TRAINER_DARIUS                          803
#define TRAINER_STEVEN                          804
#define TRAINER_ANABEL                          805
#define TRAINER_TUCKER                          806
#define TRAINER_SPENSER                         807
#define TRAINER_GRETA                           808
#define TRAINER_NOLAND                          809
#define TRAINER_LUCY                            810
#define TRAINER_BRANDON                         811
#define TRAINER_ANDRES_2                        812
#define TRAINER_ANDRES_3                        813
#define TRAINER_ANDRES_4                        814
#define TRAINER_ANDRES_5                        815
#define TRAINER_CORY_2                          816
#define TRAINER_CORY_3                          817
#define TRAINER_CORY_4                          818
#define TRAINER_CORY_5                          819
#define TRAINER_PABLO_2                         820
#define TRAINER_PABLO_3                         821
#define TRAINER_PABLO_4                         822
#define TRAINER_PABLO_5                         823
#define TRAINER_KOJI_2                          824
#define TRAINER_KOJI_3                          825
#define TRAINER_KOJI_4                          826
#define TRAINER_KOJI_5                          827
#define TRAINER_CRISTIN_2                       828
#define TRAINER_CRISTIN_3                       829
#define TRAINER_CRISTIN_4                       830
#define TRAINER_CRISTIN_5                       831
#define TRAINER_FERNANDO_2                      832
#define TRAINER_FERNANDO_3                      833
#define TRAINER_FERNANDO_4                      834
#define TRAINER_FERNANDO_5                      835
#define TRAINER_SAWYER_2                        836
#define TRAINER_SAWYER_3                        837
#define TRAINER_SAWYER_4                        838
#define TRAINER_SAWYER_5                        839
#define TRAINER_GABRIELLE_2                     840
#define TRAINER_GABRIELLE_3                     841
#define TRAINER_GABRIELLE_4                     842
#define TRAINER_GABRIELLE_5                     843
#define TRAINER_THALIA_2                        844
#define TRAINER_THALIA_3                        845
#define TRAINER_THALIA_4                        846
#define TRAINER_THALIA_5                        847
#define TRAINER_MARIELA                         848
#define TRAINER_ALVARO                          849
#define TRAINER_EVERETT                         850
#define TRAINER_RED                             851
#define TRAINER_LEAF                            852
#define TRAINER_BRENDAN_PLACEHOLDER             853
#define TRAINER_MAY_PLACEHOLDER                 854
// Kanto
#define TRAINER_YOUNGSTER_BEN                   855
#define TRAINER_YOUNGSTER_CALVIN                856
#define TRAINER_YOUNGSTER_JOSH                  857
#define TRAINER_YOUNGSTER_TIMMY                 858
#define TRAINER_YOUNGSTER_JOEY                  859
#define TRAINER_YOUNGSTER_DAN                   860
#define TRAINER_YOUNGSTER_CHAD                  861
#define TRAINER_YOUNGSTER_TYLER                 862
#define TRAINER_YOUNGSTER_EDDIE                 863
#define TRAINER_YOUNGSTER_DILLON                864
#define TRAINER_YOUNGSTER_YASU                  865
#define TRAINER_YOUNGSTER_DAVE                  866
#define TRAINER_YOUNGSTER_BEN_2                 867
#define TRAINER_BUG_CATCHER_RICK                868
#define TRAINER_BUG_CATCHER_DOUG                869
#define TRAINER_BUG_CATCHER_SAMMY               870
#define TRAINER_BUG_CATCHER_COLTON              871
#define TRAINER_BUG_CATCHER_GREG                872
#define TRAINER_BUG_CATCHER_JAMES               873
#define TRAINER_BUG_CATCHER_KENT                874
#define TRAINER_BUG_CATCHER_ROBBY               875
#define TRAINER_BUG_CATCHER_CALE                876
#define TRAINER_BUG_CATCHER_KEIGO               877
#define TRAINER_BUG_CATCHER_ELIJAH              878
#define TRAINER_BUG_CATCHER_2                   879
#define TRAINER_BUG_CATCHER_BRENT               880
#define TRAINER_BUG_CATCHER_CONNER              881
#define TRAINER_LASS_JANICE                     882
#define TRAINER_LASS_SALLY                      883
#define TRAINER_LASS_ROBIN                      884
#define TRAINER_LASS_CRISSY                     885
#define TRAINER_LASS_MIRIAM                     886
#define TRAINER_LASS_IRIS                       887
#define TRAINER_LASS_RELI                       888
#define TRAINER_LASS_ALI                        889
#define TRAINER_LASS_2                          890
#define TRAINER_LASS_HALEY                      891
#define TRAINER_LASS_ANN                        892
#define TRAINER_LASS_DAWN                       893
#define TRAINER_LASS_PAIGE                      894
#define TRAINER_LASS_ANDREA                     895
#define TRAINER_LASS_MEGAN                      896
#define TRAINER_LASS_JULIA                      897
#define TRAINER_LASS_KAY                        898
#define TRAINER_LASS_LISA                       899
#define TRAINER_SAILOR_EDMOND                   900
#define TRAINER_SAILOR_TREVOR                   901
#define TRAINER_SAILOR_LEONARD                  902
#define TRAINER_SAILOR_DUNCAN                   903
#define TRAINER_SAILOR_HUEY                     904
#define TRAINER_SAILOR_DYLAN                    905
#define TRAINER_SAILOR_PHILLIP                  906
#define TRAINER_SAILOR_DWAYNE                   907
#define TRAINER_CAMPER_LIAM                     908
#define TRAINER_CAMPER_SHANE                    909
#define TRAINER_CAMPER_ETHAN                    910
#define TRAINER_CAMPER_RICKY                    911
#define TRAINER_CAMPER_JEFF                     912
#define TRAINER_CAMPER_2                        913
#define TRAINER_CAMPER_CHRIS                    914
#define TRAINER_CAMPER_DREW                     915
#define TRAINER_PICNICKER_DIANA                 916
#define TRAINER_PICNICKER_NANCY                 917
#define TRAINER_PICNICKER_ISABELLE              918
#define TRAINER_PICNICKER_KELSEY                919
#define TRAINER_PICNICKER_ALICIA                920
#define TRAINER_PICNICKER_CAITLIN               921
#define TRAINER_PICNICKER_HEIDI                 922
#define TRAINER_PICNICKER_CAROL                 923
#define TRAINER_PICNICKER_SOFIA                 924
#define TRAINER_PICNICKER_MARTHA                925
#define TRAINER_PICNICKER_TINA                  926
#define TRAINER_PICNICKER_HANNAH                927
#define TRAINER_POKEMANIAC_MARK                 928
#define TRAINER_POKEMANIAC_HERMAN               929
#define TRAINER_POKEMANIAC_COOPER               930
#define TRAINER_POKEMANIAC_STEVE                931
#define TRAINER_POKEMANIAC_WINSTON              932
#define TRAINER_POKEMANIAC_DAWSON               933
#define TRAINER_POKEMANIAC_ASHTON               934
#define TRAINER_SUPER_NERD_JOVAN                935
#define TRAINER_SUPER_NERD_MIGUEL               936
#define TRAINER_SUPER_NERD_AIDAN                937
#define TRAINER_SUPER_NERD_GLENN                938
#define TRAINER_SUPER_NERD_LESLIE               939
#define TRAINER_SUPER_NERD_1                    940
#define TRAINER_SUPER_NERD_2                    941
#define TRAINER_SUPER_NERD_3                    942
#define TRAINER_SUPER_NERD_ERIK                 943
#define TRAINER_SUPER_NERD_AVERY                944
#define TRAINER_SUPER_NERD_DEREK                945
#define TRAINER_SUPER_NERD_ZAC                  946
#define TRAINER_HIKER_MARCOS                    947
#define TRAINER_HIKER_FRANKLIN                  948
#define TRAINER_HIKER_NOB                       949
#define TRAINER_HIKER_WAYNE                     950
#define TRAINER_HIKER_ALAN                      951
#define TRAINER_HIKER_BRICE                     952
#define TRAINER_HIKER_CLARK                     953
#define TRAINER_HIKER_TRENT                     954
#define TRAINER_HIKER_DUDLEY                    955
#define TRAINER_HIKER_ALLEN                     956
#define TRAINER_HIKER_ERIC                      957
#define TRAINER_HIKER_LENNY                     958
#define TRAINER_HIKER_OLIVER                    959
#define TRAINER_HIKER_LUCAS                     960
#define TRAINER_BIKER_JARED                     961
#define TRAINER_BIKER_MALIK                     962
#define TRAINER_BIKER_ERNEST                    963
#define TRAINER_BIKER_ALEX                      964
#define TRAINER_BIKER_LAO                       965
#define TRAINER_BIKER_1                         966
#define TRAINER_BIKER_HIDEO                     967
#define TRAINER_BIKER_RUBEN                     968
#define TRAINER_BIKER_BILLY                     969
#define TRAINER_BIKER_NIKOLAS                   970
#define TRAINER_BIKER_JAXON                     971
#define TRAINER_BIKER_WILLIAM                   972
#define TRAINER_BIKER_LUKAS                     973
#define TRAINER_BIKER_ISAAC                     974
#define TRAINER_BIKER_GERALD                    975
#define TRAINER_BURGLAR_1                       976
#define TRAINER_BURGLAR_2                       977
#define TRAINER_BURGLAR_3                       978
#define TRAINER_BURGLAR_QUINN                   979
#define TRAINER_BURGLAR_RAMON                   980
#define TRAINER_BURGLAR_DUSTY                   981
#define TRAINER_BURGLAR_ARNIE                   982
#define TRAINER_BURGLAR_4                       983
#define TRAINER_BURGLAR_SIMON                   984
#define TRAINER_BURGLAR_LEWIS                   985
#define TRAINER_ENGINEER_BAILY                  986
#define TRAINER_ENGINEER_BRAXTON                987
#define TRAINER_ENGINEER_BERNIE                 988
#define TRAINER_FISHERMAN_DALE                  989
#define TRAINER_FISHERMAN_BARNY                 990
#define TRAINER_FISHERMAN_NED                   991
#define TRAINER_FISHERMAN_CHIP                  992
#define TRAINER_FISHERMAN_HANK                  993
#define TRAINER_FISHERMAN_ELLIOT                994
#define TRAINER_FISHERMAN_RONALD                995
#define TRAINER_FISHERMAN_CLAUDE                996
#define TRAINER_FISHERMAN_WADE                  997
#define TRAINER_FISHERMAN_NOLAN                 998
#define TRAINER_FISHERMAN_ANDREW                999
#define TRAINER_SWIMMER_MALE_LUIS               1000
#define TRAINER_SWIMMER_MALE_RICHARD            1001
#define TRAINER_SWIMMER_MALE_REECE              1002
#define TRAINER_SWIMMER_MALE_MATTHEW            1003
#define TRAINER_SWIMMER_MALE_DOUGLAS            1004
#define TRAINER_SWIMMER_MALE_DAVID              1005
#define TRAINER_SWIMMER_MALE_TONY               1006
#define TRAINER_SWIMMER_MALE_AXLE               1007
#define TRAINER_SWIMMER_MALE_BARRY              1008
#define TRAINER_SWIMMER_MALE_DEAN               1009
#define TRAINER_SWIMMER_MALE_DARRIN             1010
#define TRAINER_SWIMMER_MALE_SPENCER            1011
#define TRAINER_SWIMMER_MALE_JACK               1012
#define TRAINER_SWIMMER_MALE_JEROME             1013
#define TRAINER_SWIMMER_MALE_ROLAND             1014
#define TRAINER_CUE_BALL_KOJI                   1015
#define TRAINER_CUE_BALL_LUKE                   1016
#define TRAINER_CUE_BALL_CAMRON                 1017
#define TRAINER_CUE_BALL_RAUL                   1018
#define TRAINER_CUE_BALL_ISAIAH                 1019
#define TRAINER_CUE_BALL_ZEEK                   1020
#define TRAINER_CUE_BALL_JAMAL                  1021
#define TRAINER_CUE_BALL_COREY                  1022
#define TRAINER_CUE_BALL_CHASE                  1023
#define TRAINER_GAMER_HUGO                      1024
#define TRAINER_GAMER_JASPER                    1025
#define TRAINER_GAMER_DIRK                      1026
#define TRAINER_GAMER_DARIAN                    1027
#define TRAINER_GAMER_STAN                      1028
#define TRAINER_GAMER_1                         1029
#define TRAINER_GAMER_RICH                      1030
#define TRAINER_BEAUTY_BRIDGET                  1031
#define TRAINER_BEAUTY_TAMIA                    1032
#define TRAINER_BEAUTY_LORI                     1033
#define TRAINER_BEAUTY_LOLA                     1034
#define TRAINER_BEAUTY_SHEILA                   1035
#define TRAINER_SWIMMER_FEMALE_TIFFANY          1036
#define TRAINER_SWIMMER_FEMALE_NORA             1037
#define TRAINER_SWIMMER_FEMALE_MELISSA          1038
#define TRAINER_BEAUTY_GRACE                    1039
#define TRAINER_BEAUTY_OLIVIA                   1040
#define TRAINER_BEAUTY_LAUREN                   1041
#define TRAINER_SWIMMER_FEMALE_ANYA             1042
#define TRAINER_SWIMMER_FEMALE_ALICE            1043
#define TRAINER_SWIMMER_FEMALE_CONNIE           1044
#define TRAINER_SWIMMER_FEMALE_SHIRLEY          1045
#define TRAINER_PSYCHIC_JOHAN                   1046
#define TRAINER_PSYCHIC_TYRON                   1047
#define TRAINER_PSYCHIC_CAMERON                 1048
#define TRAINER_PSYCHIC_PRESTON                 1049
#define TRAINER_ROCKER_RANDALL                  1050
#define TRAINER_ROCKER_LUCA                     1051
#define TRAINER_JUGGLER_DALTON                  1052
#define TRAINER_JUGGLER_NELSON                  1053
#define TRAINER_JUGGLER_KIRK                    1054
#define TRAINER_JUGGLER_SHAWN                   1055
#define TRAINER_JUGGLER_GREGORY                 1056
#define TRAINER_JUGGLER_EDWARD                  1057
#define TRAINER_JUGGLER_KAYDEN                  1058
#define TRAINER_JUGGLER_NATE                    1059
#define TRAINER_TAMER_PHIL                      1060
#define TRAINER_TAMER_EDGAR                     1061
#define TRAINER_TAMER_JASON                     1062
#define TRAINER_TAMER_COLE                      1063
#define TRAINER_TAMER_VINCENT                   1064
#define TRAINER_TAMER_JOHN                      1065
#define TRAINER_BIRD_KEEPER_SEBASTIAN           1066
#define TRAINER_BIRD_KEEPER_PERRY               1067
#define TRAINER_BIRD_KEEPER_ROBERT              1068
#define TRAINER_BIRD_KEEPER_DONALD              1069
#define TRAINER_BIRD_KEEPER_BENNY               1070
#define TRAINER_BIRD_KEEPER_EDWIN               1071
#define TRAINER_BIRD_KEEPER_CHESTER             1072
#define TRAINER_BIRD_KEEPER_WILTON              1073
#define TRAINER_BIRD_KEEPER_RAMIRO              1074
#define TRAINER_BIRD_KEEPER_JACOB               1075
#define TRAINER_BIRD_KEEPER_ROGER               1076
#define TRAINER_BIRD_KEEPER_REED                1077
#define TRAINER_BIRD_KEEPER_KEITH               1078
#define TRAINER_BIRD_KEEPER_CARTER              1079
#define TRAINER_BIRD_KEEPER_MITCH               1080
#define TRAINER_BIRD_KEEPER_BECK                1081
#define TRAINER_BIRD_KEEPER_MARLON              1082
#define TRAINER_BLACK_BELT_KOICHI               1083
#define TRAINER_BLACK_BELT_MIKE                 1084
#define TRAINER_BLACK_BELT_HIDEKI               1085
#define TRAINER_BLACK_BELT_AARON                1086
#define TRAINER_BLACK_BELT_HITOSHI              1087
#define TRAINER_BLACK_BELT_ATSUSHI              1088
#define TRAINER_BLACK_BELT_KIYO                 1089
#define TRAINER_BLACK_BELT_TAKASHI              1090
#define TRAINER_BLACK_BELT_DAISUKE              1091
#define TRAINER_RIVAL_OAKS_LAB_SQUIRTLE         1092
#define TRAINER_RIVAL_OAKS_LAB_BULBASAUR        1093
#define TRAINER_RIVAL_OAKS_LAB_CHARMANDER       1094
#define TRAINER_RIVAL_ROUTE22_EARLY_SQUIRTLE    1095
#define TRAINER_RIVAL_ROUTE22_EARLY_BULBASAUR   1096
#define TRAINER_RIVAL_ROUTE22_EARLY_CHARMANDER  1097
#define TRAINER_RIVAL_CERULEAN_SQUIRTLE         1098
#define TRAINER_RIVAL_CERULEAN_BULBASAUR        1099
#define TRAINER_RIVAL_CERULEAN_CHARMANDER       1100
#define TRAINER_SCIENTIST_TED                   1101
#define TRAINER_SCIENTIST_CONNOR                1102
#define TRAINER_SCIENTIST_JERRY                 1103
#define TRAINER_SCIENTIST_JOSE                  1104
#define TRAINER_SCIENTIST_RODNEY                1105
#define TRAINER_SCIENTIST_BEAU                  1106
#define TRAINER_SCIENTIST_TAYLOR                1107
#define TRAINER_SCIENTIST_JOSHUA                1108
#define TRAINER_SCIENTIST_PARKER                1109
#define TRAINER_SCIENTIST_ED                    1110
#define TRAINER_SCIENTIST_TRAVIS                1111
#define TRAINER_SCIENTIST_BRAYDON               1112
#define TRAINER_SCIENTIST_IVAN                  1113
#define TRAINER_BOSS_GIOVANNI                   1114
#define TRAINER_BOSS_GIOVANNI_2                 1115
#define TRAINER_LEADER_GIOVANNI                 1116
#define TRAINER_TEAM_ROCKET_GRUNT               1117
#define TRAINER_TEAM_ROCKET_GRUNT_2             1118
#define TRAINER_TEAM_ROCKET_GRUNT_3             1119
#define TRAINER_TEAM_ROCKET_GRUNT_4             1120
#define TRAINER_TEAM_ROCKET_GRUNT_5             1121
#define TRAINER_TEAM_ROCKET_GRUNT_6             1122
#define TRAINER_TEAM_ROCKET_GRUNT_7             1123
#define TRAINER_TEAM_ROCKET_GRUNT_8             1124
#define TRAINER_TEAM_ROCKET_GRUNT_9             1125
#define TRAINER_TEAM_ROCKET_GRUNT_10            1126
#define TRAINER_TEAM_ROCKET_GRUNT_11            1127
#define TRAINER_TEAM_ROCKET_GRUNT_12            1128
#define TRAINER_TEAM_ROCKET_GRUNT_13            1129
#define TRAINER_TEAM_ROCKET_GRUNT_14            1130
#define TRAINER_TEAM_ROCKET_GRUNT_15            1131
#define TRAINER_TEAM_ROCKET_GRUNT_16            1132
#define TRAINER_TEAM_ROCKET_GRUNT_17            1133
#define TRAINER_TEAM_ROCKET_GRUNT_18            1134
#define TRAINER_TEAM_ROCKET_GRUNT_19            1135
#define TRAINER_TEAM_ROCKET_GRUNT_20            1136
#define TRAINER_TEAM_ROCKET_GRUNT_21            1137
#define TRAINER_TEAM_ROCKET_GRUNT_22            1138
#define TRAINER_TEAM_ROCKET_GRUNT_23            1139
#define TRAINER_TEAM_ROCKET_GRUNT_24            1140
#define TRAINER_TEAM_ROCKET_GRUNT_25            1141
#define TRAINER_TEAM_ROCKET_GRUNT_26            1142
#define TRAINER_TEAM_ROCKET_GRUNT_27            1143
#define TRAINER_TEAM_ROCKET_GRUNT_28            1144
#define TRAINER_TEAM_ROCKET_GRUNT_29            1145
#define TRAINER_TEAM_ROCKET_GRUNT_30            1146
#define TRAINER_TEAM_ROCKET_GRUNT_31            1147
#define TRAINER_TEAM_ROCKET_GRUNT_32            1148
#define TRAINER_TEAM_ROCKET_GRUNT_33            1149
#define TRAINER_TEAM_ROCKET_GRUNT_34            1150
#define TRAINER_TEAM_ROCKET_GRUNT_35            1151
#define TRAINER_TEAM_ROCKET_GRUNT_36            1152
#define TRAINER_TEAM_ROCKET_GRUNT_37            1153
#define TRAINER_TEAM_ROCKET_GRUNT_38            1154
#define TRAINER_TEAM_ROCKET_GRUNT_39            1155
#define TRAINER_TEAM_ROCKET_GRUNT_40            1156
#define TRAINER_TEAM_ROCKET_GRUNT_41            1157
#define TRAINER_COOLTRAINER_SAMUEL              1158
#define TRAINER_COOLTRAINER_GEORGE              1159
#define TRAINER_COOLTRAINER_COLBY               1160
#define TRAINER_COOLTRAINER_PAUL                1161
#define TRAINER_COOLTRAINER_ROLANDO             1162
#define TRAINER_COOLTRAINER_GILBERT             1163
#define TRAINER_COOLTRAINER_OWEN                1164
#define TRAINER_COOLTRAINER_BERKE               1165
#define TRAINER_COOLTRAINER_YUJI                1166
#define TRAINER_COOLTRAINER_WARREN              1167
#define TRAINER_COOLTRAINER_MARY                1168
#define TRAINER_COOLTRAINER_CAROLINE            1169
#define TRAINER_COOLTRAINER_ALEXA               1170
#define TRAINER_COOLTRAINER_SHANNON             1171
#define TRAINER_COOLTRAINER_NAOMI               1172
#define TRAINER_COOLTRAINER_BROOKE              1173
#define TRAINER_COOLTRAINER_AUSTINA             1174
#define TRAINER_COOLTRAINER_JULIE               1175
#define TRAINER_ELITE_FOUR_LORELEI              1176
#define TRAINER_ELITE_FOUR_BRUNO                1177
#define TRAINER_ELITE_FOUR_AGATHA               1178
#define TRAINER_ELITE_FOUR_LANCE                1179
#define TRAINER_LEADER_BROCK                    1180
#define TRAINER_LEADER_MISTY                    1181
#define TRAINER_LEADER_LT_SURGE                 1182
#define TRAINER_LEADER_ERIKA                    1183
#define TRAINER_LEADER_KOGA                     1184
#define TRAINER_LEADER_BLAINE                   1185
#define TRAINER_LEADER_SABRINA                  1186
#define TRAINER_GENTLEMAN_THOMAS                1187
#define TRAINER_GENTLEMAN_ARTHUR                1188
#define TRAINER_GENTLEMAN_TUCKER                1189
#define TRAINER_GENTLEMAN_NORTON                1190
#define TRAINER_GENTLEMAN_WALTER                1191
#define TRAINER_RIVAL_SS_ANNE_SQUIRTLE          1192
#define TRAINER_RIVAL_SS_ANNE_BULBASAUR         1193
#define TRAINER_RIVAL_SS_ANNE_CHARMANDER        1194
#define TRAINER_RIVAL_POKEMON_TOWER_SQUIRTLE    1195
#define TRAINER_RIVAL_POKEMON_TOWER_BULBASAUR   1196
#define TRAINER_RIVAL_POKEMON_TOWER_CHARMANDER  1197
#define TRAINER_RIVAL_SILPH_SQUIRTLE            1198
#define TRAINER_RIVAL_SILPH_BULBASAUR           1199
#define TRAINER_RIVAL_SILPH_CHARMANDER          1200
#define TRAINER_RIVAL_ROUTE22_LATE_SQUIRTLE     1201
#define TRAINER_RIVAL_ROUTE22_LATE_BULBASAUR    1202
#define TRAINER_RIVAL_ROUTE22_LATE_CHARMANDER   1203
#define TRAINER_CHAMPION_FIRST_SQUIRTLE         1204
#define TRAINER_CHAMPION_FIRST_BULBASAUR        1205
#define TRAINER_CHAMPION_FIRST_CHARMANDER       1206
#define TRAINER_CHANNELER_PATRICIA              1207
#define TRAINER_CHANNELER_CARLY                 1208
#define TRAINER_CHANNELER_HOPE                  1209
#define TRAINER_CHANNELER_PAULA                 1210
#define TRAINER_CHANNELER_LAUREL                1211
#define TRAINER_CHANNELER_JODY                  1212
#define TRAINER_CHANNELER_TAMMY                 1213
#define TRAINER_CHANNELER_RUTH                  1214
#define TRAINER_CHANNELER_KARINA                1215
#define TRAINER_CHANNELER_JANAE                 1216
#define TRAINER_CHANNELER_ANGELICA              1217
#define TRAINER_CHANNELER_EMILIA                1218
#define TRAINER_CHANNELER_JENNIFER              1219
#define TRAINER_CHANNELER_1                     1220
#define TRAINER_CHANNELER_2                     1221
#define TRAINER_CHANNELER_3                     1222
#define TRAINER_CHANNELER_4                     1223
#define TRAINER_CHANNELER_5                     1224
#define TRAINER_CHANNELER_6                     1225
#define TRAINER_CHANNELER_7                     1226
#define TRAINER_CHANNELER_8                     1227
#define TRAINER_CHANNELER_AMANDA                1228
#define TRAINER_CHANNELER_STACY                 1229
#define TRAINER_CHANNELER_TASHA                 1230
#define TRAINER_HIKER_JEREMY                    1231
#define TRAINER_PICNICKER_ALMA                  1232
#define TRAINER_PICNICKER_SUSIE                 1233
#define TRAINER_PICNICKER_VALERIE               1234
#define TRAINER_PICNICKER_GWEN                  1235
#define TRAINER_BIKER_VIRGIL                    1236
#define TRAINER_CAMPER_FLINT                    1237
#define TRAINER_PICNICKER_MISSY                 1238
#define TRAINER_PICNICKER_IRENE                 1239
#define TRAINER_PICNICKER_DANA                  1240
#define TRAINER_PICNICKER_ARIANA                1241
#define TRAINER_PICNICKER_LEAH                  1242
#define TRAINER_CAMPER_JUSTIN                   1243
#define TRAINER_PICNICKER_YAZMIN                1244
#define TRAINER_PICNICKER_KINDRA                1245
#define TRAINER_PICNICKER_BECKY                 1246
#define TRAINER_PICNICKER_CELIA                 1247
#define TRAINER_GENTLEMAN_BROOKS                1248
#define TRAINER_GENTLEMAN_LAMAR                 1249
#define TRAINER_TWINS_ELI_ANNE                  1250
#define TRAINER_COOL_COUPLE_RAY_TYRA            1251
#define TRAINER_YOUNG_COUPLE_GIA_JES            1252
#define TRAINER_TWINS_KIRI_JAN                  1253
#define TRAINER_CRUSH_KIN_RON_MYA               1254
#define TRAINER_YOUNG_COUPLE_LEA_JED            1255
#define TRAINER_SIS_AND_BRO_LIA_LUC             1256
#define TRAINER_SIS_AND_BRO_LIL_IAN             1257
#define TRAINER_BUG_CATCHER_3                   1258
#define TRAINER_BUG_CATCHER_4                   1259
#define TRAINER_BUG_CATCHER_5                   1260
#define TRAINER_BUG_CATCHER_6                   1261
#define TRAINER_BUG_CATCHER_7                   1262
#define TRAINER_BUG_CATCHER_8                   1263
#define TRAINER_YOUNGSTER_BEN_3                 1264
#define TRAINER_YOUNGSTER_BEN_4                 1265
#define TRAINER_YOUNGSTER_CHAD_2                1266
#define TRAINER_LASS_RELI_2                     1267
#define TRAINER_LASS_RELI_3                     1268
#define TRAINER_YOUNGSTER_TIMMY_2               1269
#define TRAINER_YOUNGSTER_TIMMY_3               1270
#define TRAINER_YOUNGSTER_TIMMY_4               1271
#define TRAINER_YOUNGSTER_CHAD_3                1272
#define TRAINER_LASS_JANICE_2                   1273
#define TRAINER_LASS_JANICE_3                   1274
#define TRAINER_YOUNGSTER_CHAD_4                1275
#define TRAINER_HIKER_FRANKLIN_2                1276
#define TRAINER_PKMN_PROF_PROF_OAK              1277
#define TRAINER_PLAYER_BRENDAN                  1278
#define TRAINER_PLAYER_MAY                      1279
#define TRAINER_PLAYER_RED                      1280
#define TRAINER_PLAYER_LEAF                     1281
#define TRAINER_TEAM_ROCKET_GRUNT_42            1282
#define TRAINER_PSYCHIC_JACLYN                  1283
#define TRAINER_CRUSH_GIRL_SHARON               1284
#define TRAINER_TUBER_AMIRA                     1285
#define TRAINER_PKMN_BREEDER_ALIZE              1286
#define TRAINER_PKMN_RANGER_NICOLAS             1287
#define TRAINER_PKMN_RANGER_MADELINE            1288
#define TRAINER_AROMA_LADY_NIKKI                1289
#define TRAINER_RUIN_MANIAC_STANLY              1290
#define TRAINER_LADY_JACKI                      1291
#define TRAINER_PAINTER_DAISY                   1292
#define TRAINER_BIKER_GOON                      1293
#define TRAINER_BIKER_GOON_2                    1294
#define TRAINER_BIKER_GOON_3                    1295
#define TRAINER_BIKER_2                         1296
#define TRAINER_BUG_CATCHER_ANTHONY             1297
#define TRAINER_BUG_CATCHER_CHARLIE             1298
#define TRAINER_TWINS_ELI_ANNE_2                1299
#define TRAINER_YOUNGSTER_JOHNSON               1300
#define TRAINER_BIKER_RICARDO                   1301
#define TRAINER_BIKER_JAREN                     1302
#define TRAINER_TEAM_ROCKET_GRUNT_43            1303
#define TRAINER_TEAM_ROCKET_GRUNT_44            1304
#define TRAINER_TEAM_ROCKET_GRUNT_45            1305
#define TRAINER_TEAM_ROCKET_GRUNT_46            1306
#define TRAINER_TEAM_ROCKET_GRUNT_47            1307
#define TRAINER_TEAM_ROCKET_GRUNT_48            1308
#define TRAINER_TEAM_ROCKET_ADMIN               1309
#define TRAINER_TEAM_ROCKET_ADMIN_2             1310
#define TRAINER_SCIENTIST_GIDEON                1311
#define TRAINER_SWIMMER_FEMALE_AMARA            1312
#define TRAINER_SWIMMER_FEMALE_MARIA            1313
#define TRAINER_SWIMMER_FEMALE_ABIGAIL          1314
#define TRAINER_SWIMMER_MALE_FINN               1315
#define TRAINER_SWIMMER_MALE_GARRETT            1316
#define TRAINER_FISHERMAN_TOMMY                 1317
#define TRAINER_CRUSH_GIRL_TANYA                1318
#define TRAINER_BLACK_BELT_SHEA                 1319
#define TRAINER_BLACK_BELT_HUGH                 1320
#define TRAINER_CAMPER_BRYCE                    1321
#define TRAINER_PICNICKER_CLAIRE                1322
#define TRAINER_CRUSH_KIN_MIK_KIA               1323
#define TRAINER_AROMA_LADY_VIOLET               1324
#define TRAINER_TUBER_ALEXIS                    1325
#define TRAINER_TWINS_JOY_MEG                   1326
#define TRAINER_SWIMMER_FEMALE_TISHA            1327
#define TRAINER_PAINTER_CELINA                  1328
#define TRAINER_PAINTER_RAYNA                   1329
#define TRAINER_LADY_GILLIAN                    1330
#define TRAINER_YOUNGSTER_DESTIN                1331
#define TRAINER_SWIMMER_MALE_TOBY               1332
#define TRAINER_TEAM_ROCKET_GRUNT_49            1333
#define TRAINER_TEAM_ROCKET_GRUNT_50            1334
#define TRAINER_TEAM_ROCKET_GRUNT_51            1335
#define TRAINER_BIRD_KEEPER_MILO                1336
#define TRAINER_BIRD_KEEPER_CHAZ                1337
#define TRAINER_BIRD_KEEPER_HAROLD              1338
#define TRAINER_FISHERMAN_TYLOR                 1339
#define TRAINER_SWIMMER_MALE_MYMO               1340
#define TRAINER_SWIMMER_FEMALE_NICOLE           1341
#define TRAINER_SIS_AND_BRO_AVA_GEB             1342
#define TRAINER_AROMA_LADY_ROSE                 1343
#define TRAINER_SWIMMER_MALE_SAMIR              1344
#define TRAINER_SWIMMER_FEMALE_DENISE           1345
#define TRAINER_TWINS_MIU_MIA                   1346
#define TRAINER_HIKER_EARL                      1347
#define TRAINER_RUIN_MANIAC_FOSTER              1348
#define TRAINER_RUIN_MANIAC_LARRY               1349
#define TRAINER_HIKER_DARYL                     1350
#define TRAINER_POKEMANIAC_HECTOR               1351
#define TRAINER_PSYCHIC_DARIO                   1352
#define TRAINER_PSYCHIC_RODETTE                 1353
#define TRAINER_AROMA_LADY_MIAH                 1354
#define TRAINER_YOUNG_COUPLE_EVE_JON            1355
#define TRAINER_JUGGLER_MASON                   1356
#define TRAINER_CRUSH_GIRL_CYNDY                1357
#define TRAINER_CRUSH_GIRL_JOCELYN              1358
#define TRAINER_TAMER_EVAN                      1359
#define TRAINER_POKEMANIAC_MARK_2               1360
#define TRAINER_PKMN_RANGER_LOGAN               1361
#define TRAINER_PKMN_RANGER_JACKSON             1362
#define TRAINER_PKMN_RANGER_BETH                1363
#define TRAINER_PKMN_RANGER_KATELYN             1364
#define TRAINER_COOLTRAINER_LEROY               1365
#define TRAINER_COOLTRAINER_MICHELLE            1366
#define TRAINER_COOL_COUPLE_LEX_NYA             1367
#define TRAINER_RUIN_MANIAC_BRANDON             1368
#define TRAINER_RUIN_MANIAC_BENJAMIN            1369
#define TRAINER_PAINTER_EDNA                    1370
#define TRAINER_GENTLEMAN_CLIFFORD              1371
#define TRAINER_LADY_SELPHY                     1372
#define TRAINER_RUIN_MANIAC_LAWSON              1373
#define TRAINER_PSYCHIC_LAURA                   1374
#define TRAINER_PKMN_BREEDER_BETHANY            1375
#define TRAINER_PKMN_BREEDER_ALLISON            1376
#define TRAINER_BUG_CATCHER_GARRET              1377
#define TRAINER_BUG_CATCHER_JONAH               1378
#define TRAINER_BUG_CATCHER_VANCE               1379
#define TRAINER_YOUNGSTER_NASH                  1380
#define TRAINER_YOUNGSTER_CORDELL               1381
#define TRAINER_LASS_DALIA                      1382
#define TRAINER_LASS_JOANA                      1383
#define TRAINER_CAMPER_RILEY                    1384
#define TRAINER_PICNICKER_MARCY                 1385
#define TRAINER_RUIN_MANIAC_LAYTON              1386
#define TRAINER_PICNICKER_KELSEY_2              1387
#define TRAINER_PICNICKER_KELSEY_3              1388
#define TRAINER_PICNICKER_KELSEY_4              1389
#define TRAINER_CAMPER_RICKY_2                  1390
#define TRAINER_CAMPER_RICKY_3                  1391
#define TRAINER_CAMPER_RICKY_4                  1392
#define TRAINER_CAMPER_JEFF_2                   1393
#define TRAINER_CAMPER_JEFF_3                   1394
#define TRAINER_CAMPER_JEFF_4                   1395
#define TRAINER_PICNICKER_ISABELLE_2            1396
#define TRAINER_PICNICKER_ISABELLE_3            1397
#define TRAINER_PICNICKER_ISABELLE_4            1398
#define TRAINER_YOUNGSTER_YASU_2                1399
#define TRAINER_YOUNGSTER_YASU_3                1400
#define TRAINER_ENGINEER_BERNIE_2               1401
#define TRAINER_GAMER_DARIAN_2                  1402
#define TRAINER_CAMPER_CHRIS_2                  1403
#define TRAINER_CAMPER_CHRIS_3                  1404
#define TRAINER_CAMPER_CHRIS_4                  1405
#define TRAINER_PICNICKER_ALICIA_2              1406
#define TRAINER_PICNICKER_ALICIA_3              1407
#define TRAINER_PICNICKER_ALICIA_4              1408
#define TRAINER_HIKER_JEREMY_2                  1409
#define TRAINER_POKEMANIAC_MARK_3               1410
#define TRAINER_POKEMANIAC_HERMAN_2             1411
#define TRAINER_POKEMANIAC_HERMAN_3             1412
#define TRAINER_HIKER_TRENT_2                   1413
#define TRAINER_LASS_MEGAN_2                    1414
#define TRAINER_LASS_MEGAN_3                    1415
#define TRAINER_SUPER_NERD_GLENN_2              1416
#define TRAINER_GAMER_RICH_2                    1417
#define TRAINER_BIKER_JAREN_2                   1418
#define TRAINER_FISHERMAN_ELLIOT_2              1419
#define TRAINER_ROCKER_LUCA_2                   1420
#define TRAINER_BEAUTY_SHEILA_2                 1421
#define TRAINER_BIRD_KEEPER_ROBERT_2            1422
#define TRAINER_BIRD_KEEPER_ROBERT_3            1423
#define TRAINER_PICNICKER_SUSIE_2               1424
#define TRAINER_PICNICKER_SUSIE_3               1425
#define TRAINER_PICNICKER_SUSIE_4               1426
#define TRAINER_BIKER_LUKAS_2                   1427
#define TRAINER_BIRD_KEEPER_BENNY_2             1428
#define TRAINER_BIRD_KEEPER_BENNY_3             1429
#define TRAINER_BIRD_KEEPER_MARLON_2            1430
#define TRAINER_BIRD_KEEPER_MARLON_3            1431
#define TRAINER_BEAUTY_GRACE_2                  1432
#define TRAINER_BIRD_KEEPER_CHESTER_2           1433
#define TRAINER_BIRD_KEEPER_CHESTER_3           1434
#define TRAINER_PICNICKER_BECKY_2               1435
#define TRAINER_PICNICKER_BECKY_3               1436
#define TRAINER_PICNICKER_BECKY_4               1437
#define TRAINER_CRUSH_KIN_RON_MYA_2             1438
#define TRAINER_CRUSH_KIN_RON_MYA_3             1439
#define TRAINER_CRUSH_KIN_RON_MYA_4             1440
#define TRAINER_BIKER_RUBEN_2                   1441
#define TRAINER_CUE_BALL_CAMRON_2               1442
#define TRAINER_BIKER_JAXON_2                   1443
#define TRAINER_CUE_BALL_ISAIAH_2               1444
#define TRAINER_CUE_BALL_COREY_2                1445
#define TRAINER_BIRD_KEEPER_JACOB_2             1446
#define TRAINER_BIRD_KEEPER_JACOB_3             1447
#define TRAINER_SWIMMER_FEMALE_ALICE_2          1448
#define TRAINER_SWIMMER_MALE_DARRIN_2           1449
#define TRAINER_PICNICKER_MISSY_2               1450
#define TRAINER_PICNICKER_MISSY_3               1451
#define TRAINER_FISHERMAN_WADE_2                1452
#define TRAINER_SWIMMER_MALE_JACK_2             1453
#define TRAINER_SIS_AND_BRO_LIL_IAN_2           1454
#define TRAINER_SIS_AND_BRO_LIL_IAN_3           1455
#define TRAINER_SWIMMER_MALE_FINN_2             1456
#define TRAINER_CRUSH_GIRL_SHARON_2             1457
#define TRAINER_CRUSH_GIRL_SHARON_3             1458
#define TRAINER_CRUSH_GIRL_TANYA_2              1459
#define TRAINER_CRUSH_GIRL_TANYA_3              1460
#define TRAINER_BLACK_BELT_SHEA_2               1461
#define TRAINER_BLACK_BELT_SHEA_3               1462
#define TRAINER_BLACK_BELT_HUGH_2               1463
#define TRAINER_BLACK_BELT_HUGH_3               1464
#define TRAINER_CRUSH_KIN_MIK_KIA_2             1465
#define TRAINER_CRUSH_KIN_MIK_KIA_3             1466
#define TRAINER_TUBER_AMIRA_2                   1467
#define TRAINER_TWINS_JOY_MEG_2                 1468
#define TRAINER_PAINTER_RAYNA_2                 1469
#define TRAINER_YOUNGSTER_DESTIN_2              1470
#define TRAINER_PKMN_BREEDER_ALIZE_2            1471
#define TRAINER_YOUNG_COUPLE_GIA_JES_2          1472
#define TRAINER_YOUNG_COUPLE_GIA_JES_3          1473
#define TRAINER_BIRD_KEEPER_MILO_2              1474
#define TRAINER_BIRD_KEEPER_CHAZ_2              1475
#define TRAINER_BIRD_KEEPER_HAROLD_2            1476
#define TRAINER_SWIMMER_FEMALE_NICOLE_2         1477
#define TRAINER_PSYCHIC_JACLYN_2                1478
#define TRAINER_SWIMMER_MALE_SAMIR_2            1479
#define TRAINER_HIKER_EARL_2                    1480
#define TRAINER_RUIN_MANIAC_LARRY_2             1481
#define TRAINER_POKEMANIAC_HECTOR_2             1482
#define TRAINER_PSYCHIC_DARIO_2                 1483
#define TRAINER_PSYCHIC_RODETTE_2               1484
#define TRAINER_JUGGLER_MASON_2                 1485
#define TRAINER_PKMN_RANGER_NICOLAS_2           1486
#define TRAINER_PKMN_RANGER_MADELINE_2          1487
#define TRAINER_CRUSH_GIRL_CYNDY_2              1488
#define TRAINER_TAMER_EVAN_2                    1489
#define TRAINER_PKMN_RANGER_JACKSON_2           1490
#define TRAINER_PKMN_RANGER_KATELYN_2           1491
#define TRAINER_COOLTRAINER_LEROY_2             1492
#define TRAINER_COOLTRAINER_MICHELLE_2          1493
#define TRAINER_COOL_COUPLE_LEX_NYA_2           1494
#define TRAINER_BUG_CATCHER_COLTON_2            1495
#define TRAINER_BUG_CATCHER_COLTON_3            1496
#define TRAINER_BUG_CATCHER_COLTON_4            1497
#define TRAINER_SWIMMER_MALE_MATTHEW_2          1498
#define TRAINER_SWIMMER_MALE_TONY_2             1499
#define TRAINER_SWIMMER_FEMALE_MELISSA_2        1500
#define TRAINER_ELITE_FOUR_LORELEI_2            1501
#define TRAINER_ELITE_FOUR_BRUNO_2              1502
#define TRAINER_ELITE_FOUR_AGATHA_2             1503
#define TRAINER_ELITE_FOUR_LANCE_2              1504
#define TRAINER_CHAMPION_REMATCH_SQUIRTLE       1505
#define TRAINER_CHAMPION_REMATCH_BULBASAUR      1506
#define TRAINER_CHAMPION_REMATCH_CHARMANDER     1507
#define TRAINER_CUE_BALL_PAXTON                 1508

#define TRAINERS_COUNT                          1509
#define MAX_TRAINERS_COUNT                      1535
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H
